#!/usr/bin/env ruby

ROOT=File.expand_path(File.join(__FILE__, '..'))

PROCESSES=[]

require 'open3'
require 'rainbow/ext/string'

class SubProcess
  attr_reader :name
  attr_reader :command
  attr_reader :env

  attr_reader :stdin, :stdout, :stderr

  def initialize(name, command, env = {})
    @name    = name
    @command = command
    @env     = env
  end

  def start
    @stdin, @stdout, @stderr, @wait_thr = Open3.popen3(env, command)
    @pid = @wait_thr[:pid]
  end

  def stop
    kill("TERM")
    @wait_thr.value
  end

  def running?
    @wait_thr && @wait_thr.alive?
  rescue Errno::ESRCH
    false
  end

  private

  def kill(signal)
    ::Process.kill(signal, @pid)
  end
end

at_exit do
  puts "Shutting down..."

  PROCESSES.each do |process|
    puts "Stopping #{process.name}"
    if process.running?
      process.stop
      sleep 2
      if process.running?
        process.send(:kill, "KILL")
      end
    end
  end
end

trap "SIGINT" do
  exit
end

Dir.chdir(ROOT) do
  PROCESSES << SubProcess.new(:mysql,       "mysqld --datadir='#{ROOT}/tmp/mysql' -P '5543' --socket='#{ROOT}/tmp/mysql.sock'")
  PROCESSES << SubProcess.new(:postgres,    "postgres -D 'tmp/postgres' -p '5544' -c 'synchronous_commit=off'")
  PROCESSES << SubProcess.new(:mongo,       "mongod --dbpath 'tmp/mongodb' --port '5545'")
  PROCESSES << SubProcess.new(:mailcatcher, "mailcatcher -fv")

  PROCESSES.each do |process|
    puts "Starting #{process.command}"
    process.start
  end
end

printer = Thread.new do
  begin
    loop do
      io = IO.select(PROCESSES.map(&:stdout) + PROCESSES.map(&:stderr), nil, nil, 1)

      if io.nil?
        # nothing
      else
        io.first.each do |reader|
          next if reader.eof?

          process = PROCESSES.find { |process| process.stdout == reader || process.stderr == reader }
          data = reader.gets
          width = PROCESSES.map { |process| process.name.to_s.size }.max + 3

          print "[#{process.name}] ".ljust(width).color(:magenta)
          print data.strip
          puts

        end
      end
    end
  rescue Exception => e
    puts e.message
    puts e.backtrace.inspect
  end
end

printer.join
